services:

  postgres:
    image: postgres:15

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    ports:
      - "5432:5432"

  airflow-init:
    build: .

    depends_on:
      - postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/keys/sodium-hope-496414-q7-67bd82e4d356.json

    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./keys:/opt/airflow/keys
      - ../data:/opt/airflow/data
      - ../schema:/opt/airflow/schema

    user: "50000:0"

    command: >
      bash -c "
      airflow db init &&
      airflow users create
      --username admin
      --password admin
      --firstname admin
      --lastname user
      --role Admin
      --email admin@example.com
      "

  airflow-webserver:
    build: .

    depends_on:
      - postgres
      - airflow-init

    restart: always

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/keys/sodium-hope-496414-q7-67bd82e4d356.json

    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./keys:/opt/airflow/keys
      - ../data:/opt/airflow/data
      - ../schema:/opt/airflow/schema

    user: "50000:0"

    command: webserver

    ports:
      - "8080:8080"

  airflow-scheduler:
    build: .

    depends_on:
      - postgres
      - airflow-init

    restart: always

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/keys/sodium-hope-496414-q7-67bd82e4d356.json

    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./keys:/opt/airflow/keys
      - ../data:/opt/airflow/data
      - ../schema:/opt/airflow/schema

    user: "50000:0"

    command: scheduler